### ISSUE TITLE
Events.clearEnrichments should clear enrichments for all parent context

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/core-java#1000]
Current implementation clears enrichments only for the current context and its origin, but in theory, the `origin` of the current context origin can also have enrichment.

In order to be sure that **no** enrichments are stored, the `clearEnrichments` should recursively clear enrichments from origins.

**Comment by armiol** [comment]
@dmitrykuzmin Let's have `clearEnrichments` to clear the first level only. And another API call to clear them all.
