### ISSUE TITLE
Migrate tests to Truth-based API and deprecate non-Truth one

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#1066]
We need to migrate our tests to Truth-based API of `BlackBoxBoundedContext`, and then deprecate the “other” side of its API.

**Comment by armiol** [comment]
@dmdashenkov please check if this has been done already.

**Comment by dmdashenkov** [comment]
This is done now. The only thing left is to delete the old API. We have to check with our colleagues if they still use it.
