### ISSUE TITLE
Allow register abstract dispatchers in `BoundedContextBuilder`

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#1099]
Currently, `BoundedContext` allows registering entity repositories, `EventDispatcher`s, `CommandDispatcher`s, and entity classes. `BoundedContextBuilder`, on the other hand, allows only to register entity repositories.

We need to add `add(..)` method overloads for the other registration options.

Once this is done, we need to make sure that `BlackBoxBoundedContext.from(BoundedContextBuilder)` also will take the registered abstract dispatchers.

**Comment by dmitrykuzmin** [comment]
Done with #1100.
