### ISSUE TITLE
Duplicates in `AggregateRepository` and `ProcessManagerRepository`

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#1109]
Currently, repositories for aggregates and PMs do not have any common interface/implementation base but the `Repository` itself despite having many features in common.

It is possible to extract a common base via default methods. This would require making `Repository` an interface.

Possibly, we could still extract common parts via composition.

**Comment by alexander-yevsyukov** [comment]
Addressed in #1172.
