### ISSUE TITLE
Introduce `Entity` column option for Protobuf `Entity` state definitions

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/core-java#1135]
Currently, the entity columns are defined in Java with `@Column` annotation.

While this is convenient, it's completely invisible for those who use them for querying or subscribing to `Entity` state updates.

Therefore it is proposed to introduce a `(column)` option.

```proto
message UserProfile {
    option (entity).kind = PROJECTION;

    UserId id = 1;

    // ...

    // When this user was registered in the system.
    google.protobuf.Timestamp when_registered = 7 [(required) = true];
    
    // A year of user's registration in the system.
    int32 year_of_registration = 8 [(column) = true];    
}
```

A presence of `[(column) = true]` implies optionality of the marked field.

End-users will have two options to set the value for the column:

1. Use Spine-generated interface when declaring their entity. E.g.

```java
interface UserProfileWithColumns extends EntityWithColumns {
    
    int getYearOfRegistration();
}

// ...
class UserProfileProjection 
            extends Projection<UserId, UserProfile, UserProfile.Builder>
            implements UserProfileWithColumns { ... }
```
In which case this method becomes mandatory for implementation. The framework routines will then be able to call the methods in all `T extends EntityWithColumns` entity classes.

2. Fill the value in manually when updating the `Entity` state.

In both cases, the `year_of_registration` column value should be finalized by the moment of transaction commit. If an end-user decides to leave it empty — that's what the framework will count as an intentional action.

In this way, the dictionary of the language shared between a server and its clients will have a clear notion of what can be used for querying and subscribing.

**Comment by dmitrykuzmin** [comment]
Closed with [base#492](https://github.com/SpineEventEngine/base/pull/492), #1184.
