### ISSUE TITLE
Demystify “Idempotence Source” and “Idempotence Window”

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#1165]
We have a number of occasions where we have something like:

```java
ImmutableList<InboxMessage> idempotenceSource = classifier.idempotenceSource();
```
or
```java
private DeliveryErrors
    deliverByType(ImmutableList<InboxMessage> toDeliver, ImmutableList<InboxMessage> idmptSource) { ... }
```

The nature of the concept of the “Idemportance Source” is unclear. It is needed to encapsulate this list of messages into a class with this name and document it accordingly.

We also have a concept of “Idempotence Window”, which is duration of something, which also needs explanation.

**Comment by alexander-yevsyukov** [comment]
@armiol, FYI.

**Comment by armiol** [comment]
We don't mention these things in the documentation and the codebase anymore.
