### ISSUE TITLE
Use `@Where` in commanders and reactors

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/core-java#1203]
It's currently possible to use the filtering capabilities (the `@Where` annotation) in `@Subscriber`s while it looks like we can expose the same functionality to `@React` and `@Command`:

```java
@Command
NotifyAdministrator on(@Where(...) TaskCreated event) {
   ...
}

@React
TaskAssigned on(@Where(...) TaskCreated event) {
    ...
}
```

**Comment by armiol** [comment]
Closing as per discussion in #1204.
