### ISSUE TITLE
Consider evaluating cloud-agnostic PubSub alternatives

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/core-java#1208]
We currently use PubSub GCP service as our delivery transport, but it may be an issue for developers that do not use GCP at all. Maybe we should consider looking at cloud-agnostic PubSub alternatives.
Here is one of the products that look promising: [PubSub+ Platform](https://solace.com/products/platform/) by [Solace](https://solace.com). (here is their [datasheet](https://solace.com/wp-content/uploads/2019/11/PubSub-Plus-Cloud-Datasheet.pdf))

It's possible to use their platform both on-prem and as a SaaS. Maybe using them as our default delivery transport will make the framework more attractive to non-GCP developers.

**Comment by alexander-yevsyukov** [comment]
I don't think we'd make them our _default_ transport. But it does look like a good integration solution for non-GCP or multi-cloud systems.

**Comment by yuri-sergiichuk** [comment]
Here is one another alternative we may want to take into account: https://pulsar.apache.org/

**Comment by armiol** [comment]
Closing as irrelevant to the framework. We do not provide any default implementation at the moment and hardly will.
