### ISSUE TITLE
The `Migration` result is not stored if it is equal to `entityStateWithColumns`

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/core-java#1297]
## The issue

A custom `Migration` does not modify the entity state if the modified state is equal to the `entityStateWithColumns`.

## Expected result

Any result of a custom `Migration` should modify the entity state.

## More details
If one has written a custom migration that for some reason produced the same result as the `entityStateWithColumns`, the migration result is not applied.

Consider the following Process to be migrated:
```proto
message Project {
    option (entity).kind = PROCESS_MANAGER;

    ProjectId id = 1;
    string name = 2 [(column) = true];
    repeated Task task = 3;

    enum Status {
        UNDEFINED = 0;
        CREATED = 1;
        STARTED = 2;
        DONE = 3;
        CANCELLED = 4;
    }
    Status status = 4;

    string id_string = 5 [(column) = true];
}
```

Let's assume that we have an oldish process state in the storage and want to perform its migration.
While doing the migrating, we set to `id_string` to the `id` field value:

```java
    @Override
    public Project apply(Project project) {
        ProjectId id = id();
        Project result = project
                .toBuilder()
                .setIdString(id.toString())
                .vBuild();
        return result;
    }
```

And in the process manager itself, we have the `id_string` column defined as:
```java

    @Override
    public String getIdString() {
        return id().toString();
    }
```

When we apply the migration, the `id_string` value is set to the ID field value. Then, when the migration transaction is going to be committed the `Transaction#updateColumns` method is triggered, but `stateWithColumns` value is now just equal to the migrated one and thus the entity state is not updated:

```java
private void updateColumns() {
        S stateWithColumns = stateWithColumns();
        if (!stateWithColumns.equals(entity.state())) {
            entity.updateState(stateWithColumns);                 <----- This updateState is never called
        }
    }
```

See the test case here: https://github.com/SpineEventEngine/core-java/commit/75b579495774e270f3ac2ad924f7587ec13f06bc#diff-04de199876e461313a5f827e087e59edR692

**Comment by alexander-yevsyukov** [comment]
@yuri-sergiichuk, please describe the essence of what does not work and how it should be.
