### ISSUE TITLE
`Environment` and the related API could benefit from some QoL changes

### ISSUE THREAD

**Issue by dmitrykuzmin** [SpineEventEngine/core-java#1304]
A couple of suggested enhancements for custom environments and the related API:

1. There should be a possibility to lazy-init values passed to `ServerEnvironment.use(...)`.

It's often impossible to instantiate the environment-dependent values outside of the respective environment. 
For example, Google App Engine provides some static data like `GoogleCredentials.getApplicationDefault()`, which is available only when running inside an App Engine node.
In such cases, the user is forced to write code like this:
```java
if (Environment.instance().is(AppEngine.class)) {
    ServerEnvironment.use(Storage.datastore(), AppEngine.class);
}        
```
Also, even if the value creation is possible, it may lead to unnecessary resource allocation, like establishing a DB connection for the storage which won't ever be used.
As a solution, a method overload could, for example, accept `Supplier`s instead of actual values:
```java
public ServerEnvironment use(Supplier<StorageFactory> factory, Class<? extends EnvironmentType> type) {
    // ...
}

// And so on.
```

2. The `Environment.instance().is(Class)` expression could be wrapped in a static shortcut. For example: `Environment.detect(Class)`. 

Such method would also return `boolean` and would reduce the verbosity in the calling code, allowing better-looking alignment in `if`s.
This method would be useful because the Spine-based applications can have custom env-dependent variables in addition to those declared in `ServerEnvironment`. As neither `EnvSetting` nor anything similar are exposed to the users, the applications have to rely on `Environment.instance().is(Class)` to configure such values.

**Comment by alexander-yevsyukov** [comment]
> Environment.instance().is(Class)
If you have a repeated need for detecting the environment, why don't you just extract a variable instead?

**Comment by dmitrykuzmin** [comment]
> If you have a repeated need for detecting the environment, why don't you just extract a variable instead?

When I created this issue, the check was used across different methods, and creating a `static` `Environment.instance()` field felt a bit like overkill.

But now I think maybe exposing something like `EnvSetting` to the user would be even better than `Environment.detect()`. It would allow to get rid of all `if`s altogether. If we create environment-dependent `CommandScheduler` in our project, it is as much `EnvSetting`, as, for example, `StorageFactory`.

**Comment by dmitrykuzmin** [comment]
Superseded by #1315.
