### ISSUE TITLE
Custom code generation for Protobuf types

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#1334]
Protobuf is a great tool for many reasons. It serves as a bridge for data structuring across multiple languages and platforms.

We've been using Protobuf for a long time. It might be the moment now to make this tool our own. Because of that, we should research a possibility to generate code from Protobuf definitions on our own.

## Motivation

Java is the primary platform for Spine. Protobuf's support for Java is stable and exhaustive. However, there is a couple of places where generated Java code could be improved.
 1. **Readability.** Generated code is often not a very good code, in terms of human comprehension. Java code generated from Protobuf certainly is not very readable. With a careful approach to designing the generator, we could try and tackle this issue.
 2. **Performance.** Java code generated from Protobuf can sometimes be less performant then we'd like. We already generate some code to work around some unnecessary reflection calls. On practice, we could get rid of Java reflection in Protobuf types entirely.
 3. **Extensibility.** From all the platforms with which we work, Protobuf for Java provides the most extensibility in the form of insertion points. However, not all the issues can be resolved with insertion points. For this exact reason, we've redone data the validation model for a couple of times already. By generating code on our own, we could make some of the extension cases moot and provide the level of pluggability that we need for the other cases.

All of these issues relate to JS and Dart generated code. Also, unlike Java types, Dart and JS types generated from Protobuf are mutable, meaning that we miss out on the advantages of immutability in our client code. Last but not least, JS and Dart code is poorer in terms of features compared to Java. For example, the Protobuf JSON format is not supported out of the box in JS. And the code in neither language provides an analogue of the Protobuf reflection API present in Java.

## Plan of action

In the 3.0 version of the framework, we shall provide a `protoc` plugin and its supportive tooling (Gradle plugins, standalone launchers, etc.) which would generate Kotlin code for Protobuf types. The generated code should cover the functionality of the current, at that point in time, generated Java code, including Protobuf serialization.

The generated code should be multiplatform. Compilation into JVM (for server and Android), JS (for web), and native (for iOS and native server) is a key requirement.

Spine validation framework should be built into the generator with an opportunity for extension. This way, we'll no longer need to generate validation code for all platforms separately.

The generated code should support platform-specific enhancements. For example, types which represent time could be translated into `java.util.time.*` on JVM.

Also, as the next step, we could design a way to define a domain model using just Kotlin (probably, a stripped DSL).

## Alternative

If the idea of generating Kotlin and compiling it into all the target languages fails, we should try generating code for the target platforms themselves. This seems harder because of all the duplication.

## Why invent the wheel?

All of these problems separately are solved in different third-party projects. However, none of them solves all of them at once.

Also, having our own tool would allow us to make adjustments easier as the framework evolves.

**Comment by alexander-yevsyukov** [comment]
This motivation issue and related discussions gave birth to ProtoData. As such it's already complete.
