### ISSUE TITLE
Rename "Command Handler" to "Command Assignee"

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#1378]
We use the term "Command Handler" to describe an entity or a "free-range" object which accepts a command and produces one or more events, or a rejection.

However, there are two problems with this name:
 1. Signal handler methods also have "handler" in the name, but their contract is broader yet similar. This creates a constant need to add more adjectives when describing those two things in the documentation.
 2. By itself, the word "handler", much like "processor", "manager", and "service", may mean almost anything.

My suggestion is to make the name more consistent with the way we describe other similar subjects: **Subscribers** `@Subscribe`, **Reactors** `@React`, and **Assignees** are `@Assign`-ed. I realize the analogy is not ideal due to the passive voice, yet this option seems better to me than the current naming.

**Comment by dmdashenkov** [comment]
@alexander-yevsyukov, @armiol, PTAL.

**Comment by alexander-yevsyukov** [comment]
I support. It would make things easier to understand. Please proceed when time permits.
