### ISSUE TITLE
Context initialization order matters when one context reacts to other's events 

### ISSUE THREAD

**Issue by dmitrykuzmin** [SpineEventEngine/core-java#1392]
In our app, we have two contexts, "Pipelines" and "Image Processor".  "Pipelines" reacts to events emitted by "Image Processor". "Image Processor" does not expect any events from "Pipelines".

During server initialization, if "Pipelines" context is built (via `BoundedContextBuilder.build()`) before "Image Processor", the `ConfigurationChangeObserver` appears to be never invoked with the values necessary so that "Image Processor" sees the corresponding `RequestForExternalMessages`. The expected events, thus, never arrive to "Pipelines".

Our environment setup:
```java
ServerEnvironment
        .when(Production.class)
        .use(InMemoryStorageFactory.newInstance())
        .use(InMemoryTransportFactory.newInstance())
        .use(Delivery.localAsync());
```

The forced initialization order causes problems for us, because Spine `Server` stores context builders in the `HashSet`, making the order of `build()` calls unpredictable. So I assume such context initialization behavior is unintended.

**Comment by armiol** [comment]
Fixed by #1402 and #1408.
