### ISSUE TITLE
`Migration` should overwrite entity state instead of merging new state into old one

### ISSUE THREAD

**Issue by dmitrykuzmin** [SpineEventEngine/core-java#1403]
`Migration` allows to update one or more entities in the repository by applying the user-supplied state mapping.

At the moment, the `newState` returned as the result of the mapping is propagated to the entity using `mergeFrom(...)` call on the old state. This causes `repeated` and message-type fields to be overwritten only partially.

The `Migration` logic should be changed so that the `newState` completely overwrites the old one within the migration transaction.

See [this line](https://github.com/SpineEventEngine/core-java/blob/ef79164ba77298581990392dd30b1e679c62a547/server/src/main/java/io/spine/server/entity/Migration.java#L295).

**Comment by armiol** [comment]
Addressed in #1405 and #1419.
