### ISSUE TITLE
The server environment configurator has a lazy API but is not actually lazy

### ISSUE THREAD

**Issue by dmytro-kashcheiev** [SpineEventEngine/core-java#1414]
The server environment provides API to configure storage, delivery, etc using functions instead of passing variables.
```
ServerEnvironment.when(Production.class)
                 .useDelivery(env -> delivery())
		 .useStorage(env -> storage())
		...
```
This API looks lazy and you expect this function to be called only if the environment meets the `when(...)` condition. But actually, it is not lazy and invokes immediately inside `use...` method. Such kind of API is useless and probably should be removed or replaced with lazy invocation.

**Comment by armiol** [comment]
Addressed in #1421 and #1422.
