### ISSUE TITLE
Use the latest versions of ErrorProne and `spine-mc-java`

### ISSUE THREAD

**Issue by yevhenii-nadtochii** [SpineEventEngine/core-java#1446]
Now, the repository uses ErrorProne `2.10.0`. 

Despite the fact that `config` already has a newer version of ErrorProne, we can't update it in the repository. Using the latest version of ErrorProne also requires the latest `spine-mc-java` library. But due to the [bug](https://github.com/SpineEventEngine/mc-java/issues/31) in `mc-java`, using of it leads to a compilation error.

In the scope of this issue, specify the last versions of ErrorProne and `spine-mc-java`, when the mentioned bug is resolved.

**Comment by armiol** [comment]
Addressed already.
