### ISSUE TITLE
Allow an easier way to clear `(column)` values

### ISSUE THREAD

**Issue by dmitrykuzmin** [SpineEventEngine/core-java#1536]
Currently, a message `(column)` of an entity will be empty in the entity storage record only if:

a) The entity has been saved with the `(column)` absent from its state definition (e.g., for older entities).
b) A custom `ColumnMapping` is supplied, explicitly mapping certain kinds of values to a null value.

Other approaches, including calling `.clear...()` on the entity state or overriding interface-based columns and returning `null`, will not work. The latter seems to cause an exception while calling `.clear...()` will lead to the `(column)` being saved with a `ColumnType.getDefaultInstance()` value. 

This is suboptimal for us because, e.g., if we want to clear a `Timestamp` value, it will be saved to Datastore as `datetime(“1970-01-01T00:00:00Z”)`, and now all our time range queries have to account for this value explicitly. This is also a bit counterintuitive, as calling the corresponding `.has...()` method on an entity state fetched by such a `(column)` will return `false`.

**Comment by armiol** [comment]
@dmitrykuzmin How about this (in relation to Datastore and `Timestamp`):
```java
 private static final class CustomMapping extends DsColumnMapping {

        @Override
        protected void
        setupCustomMapping(
                ImmutableMap.Builder<Class<?>, ColumnTypeMapping<?, ? extends Value<?>>> builder) {
            builder.put(Timestamp.class, ofNullableTimestamp());
            builder.put(Version.class, ofVersion());
        }

        @SuppressWarnings("UnnecessaryLambda")
        private static ColumnTypeMapping<Timestamp, Value<?>> ofNullableTimestamp() {
            return timestamp -> {
                if (timestamp.equals(Timestamp.getDefaultInstance())) {
                    return NullValue.of();
                }
                return TimestampValue.of(
                        ofTimeSecondsAndNanos(timestamp.getSeconds(), timestamp.getNanos())
                );
            };
        }
}

// ...
var customMapping = new CustomMapping();
var factory = DatastoreStorageFactory
                   .newBuilder()
                   .setDatastore(datastore())
                   .setColumnMapping(customMapping)
                   .build();
```
In this way, it will be not possible to have a **meaningfully** stored `Timestamp.getDefaultInstance()`, and `null` will be stored instead in all cases.

**Comment by armiol** [comment]
@dmitrykuzmin closing this issue now. In case anything related still persists, please feel free to open a new one.
