### ISSUE TITLE
Need better documentation for `PatternOption.flag`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#180]
Now it just says:

``` protobuf
message PatternOption {
    ...
    // The regex flag.
    int32 flag = 2;
   ...
}
```

What does this flag do? Why is it of type `int32`?

**Comment by armiol** [comment]
This `int32` field is a Perl heritage in Java. 

See [Pattern class Javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html) for the available flag values and their description.

We need to re-design this declaration into something like 

```
// Flags configuring the modes of the pattern interpreter.
repeated PatternFlag flag = 2;
```

Perhaps, `PatternFlag` would be an `enum` which at build-time would be translated into a call to Java `Pattern.compile(..., flag)`.
