### ISSUE TITLE
Move Storage implementations to the related packages

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/core-java#195]
At the moment there is a dedicated `org.spine3.server.storage` package for all the related classes.

However, a significant part of the business logic covered by `...Storage` implementations in fact belongs to the `Repository` of the same kind. Therefore some of `Storage` methods are made public, while they should have been `package-access` at most.

To resolve the issue we need to move the `Storage` implementations to the related packages, leaving the `org.spine3.server.storage` package just with the base interfaces and abstract implementations. 

In-memory `Storage` implementations are treated as a part of the framework, as they are used in tests (as so the framework users will do). Thus, they should also be moved away from the `...storage.memory` package.

E.g.
- `org.spine3.server.storage.AggregateStorage`  -> `org.spine3.server.aggregate.AggregateStorage`
- `org.spine3.server.storage.memory.InMemoryAggregateStorage` -> `org.spine3.server.aggregate.InMemoryAggregateStorage`

The unit tests should be moved accordingly.

**Comment by alexander-yevsyukov** [comment]
Resolved by #267
