### ISSUE TITLE
Construction of `CommandService` isn't straigtforward

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#245]
We need to avoid passing builder instance which accumulates the map on `build()`.

A simplest way would be to pass the map into the constructor.

**Comment by armiol** [comment]
This [has been done](https://github.com/SpineEventEngine/core-java/commit/1cd869f4edda56326350733b28dec52a8e4bd11a#diff-893dc35dfeeb0a5735cb62d9a3968891R60) already.
