### ISSUE TITLE
Avoid repeatable checking of command and event classes in `ProcessManagerRepository`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#251]
`dispatchEvent()` and `dispatchCommand()` check the classes using `checkCommandClass()` and `checkEventClass()` methods correspondingly. These methods obtain the classes by analyzing the class of the projection. It's done by reflection API, which is slow. 

We need to cache event and command classes so that we don't get the classes each time we handle a command or event.

**Comment by dmdashenkov** [comment]
This is fixed now. We do not check the dispatched messages. Also, the message types are now checked at compile time.
