### ISSUE TITLE
Failure compiler should generate Javadocs

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#304]
Now generated Java code for descendants of `FailureThrowable` only have 
```java
@javax.annotation.Generated("by Spine compiler")
```

We need to have Javadoc class header, which repeats the text from a comment of corresponding failure definition from `failures.proto`.

We also need to have Javadoc for the constructor with the description of the parameters taken from fields of a failure definition.

**Comment by dmytro-grankin** [comment]
Implemented in [#59](https://github.com/SpineEventEngine/tools/pull/59).
