### ISSUE TITLE
Use FQNs in Javadocs

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#310]
In some cases Javadocs need to reference other classes. If the code does not use the referenced class, it does not import it, and in order to reference this class and not have a full name (which is hard to read) we currently import the class. This is not good because it obfuscates the _real_ dependencies of the importing class.

In order to avoid this, we need to use the following syntax in links:
```java
/**
 * ...
 * If we need to create a {@link org.spine3.base.Command Command}...
 * ...
 * {@linkplain org.spine3.event.EventBus#post(Event) Posting to EventBus} can be done ...
 *
/
```

Make sure to use short class name or any meaningful text replacement _instead_ of just FQN. We do not want FQNs in Javadocs (unless there is a really good reason for this).

Please  update:
1. the code which currently imports in order to reference a class in Javadoc. Please update all the sub-projects.
2. the coding guidelines so that all future use cases follow the above convention.

**Comment by alexander-yevsyukov** [comment]
@alexander-aleksandrov, please pay attention to `{@linkplain }` syntax. There's a difference with `{@link }`.

**Comment by alexander-yevsyukov** [comment]
@alexander-aleksandrov please see if we can turn an inspection in Codacy that can help us spotting  such issues automatically.

**Comment by alexander-aleksandrov** [comment]
Started to work on this. You can see PR [here](https://github.com/SpineEventEngine/core-java/pull/326).

**Comment by alexander-aleksandrov** [comment]
It is done please review.

**Comment by alexander-aleksandrov** [comment]
Add to [JavaCodeStyle ](https://github.com/SpineEventEngine/core-java/wiki/Java-Code-Style#fqns-in-javadoc)changes about FQN in Javadoc

**Comment by alexander-yevsyukov** [comment]
@alexander-aleksandrov please have a better code sample. Do not use BNF, please.

**Comment by alexander-aleksandrov** [comment]
@alexander-yevsyukov Issue resolved and can be closed.
