### ISSUE TITLE
Allow creating `CommandContext` with a target entity version

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#315]
The `CommandContext` message has the following field:
```protobuf
    // The version of the entity for which this command is intended.
    //
    // A client app may not fill in this attribute if the command applies to any version of the entity.
    //
    int32 target_version = 7;
```

Now `CommandFactory` does not have a method that allows passing target version.
We need to:
1. Extend `Commands.createContext()` to accept last `@Nullable` parameter `targetVersion`.
2. Have new method `CommandFactory.create(Message, int)`.

**Comment by alexander-aleksandrov** [comment]
All changes about this issue you will find [here](https://github.com/SpineEventEngine/core-java/pull/327)
