### ISSUE TITLE
`EnrichmentFunction` should have two parameters

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#318]
Now we implement `Function`, which has only one parameter in `apply()`.
We need to have `EventFunction` and `CommandFunction` that take two parameters:
* The first parameter is `Message`, which is `eventMessage` or `commandMessage`
* The second parameter is `EventContext` or `CommandContext`.

This way we won't have to inject event context into enrichment functions before calculations.

**Comment by alexander-yevsyukov** [comment]
Please check if `FieldEnricher` needs `equals()` and `hashCode()`. It looks like it does.

**Comment by alexander-yevsyukov** [comment]
After further thought, it's not really a bug. It's just an omission, which affects readability of the code. It should fixed as such.

**Comment by dmdashenkov** [comment]
Currently, an enrichment function is a bi-function of the message and context.
