### ISSUE TITLE
Keep command endpoints in `CommandBus` once found

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#320]
When a command posted to `CommandBus` it initially verifies that the command is supported by looking into `dispatcherRegistry` and `handlerRegistry`. Then when doing `doPost()` it asks them once again.

We may have an internal `Endpoint` interface that would be stored in:
a map like this;
```java
Map<CommandClass, Endpoint> endpoints;
```

The `Endpoint`would have two implementations. One would accept `CommandDispatcher`, another would accept `CommandHandler`. They would do what currently `CommandBus` does in `dispatch()` and `inkokeHandler()`.

**Comment by armiol** [comment]
This is now a part of `Model`.
