### ISSUE TITLE
Default multitenant `InMemoryStorageFactory` for tests.

### ISSUE THREAD

**Issue by IlliaShepilov** [SpineEventEngine/core-java#329]
We have no possibility to instantiate default  multi tenant `InMemoryStorageFactory` instance during the tests. Multi tenant value passed through `BoundedContext` is passing only to the `CommandBus`. Instantiated `InMemoryStorageFactory` always will be single tenant for that scenario.

**Comment by alexander-yevsyukov** [comment]
Fixed in #370.
