### ISSUE TITLE
Tag slow tests as such and run separately

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#333]
Currently the build pauses for several seconds in between. Our tests grow. 
Slow tests are going to hurt more with time.
We also want to try mutation testing, and slow tests would make those tests much much slower.

**Comment by dmdashenkov** [comment]
At this point, a local build using pre-cached dependencies takes up about 3-4 minutes. A CI build takes around 9 minutes. Since this issue was created, many time-consuming tests (in particular, multithreaded delivery tests) have been deleted.
I think, we can tolerate this build time.
