### ISSUE TITLE
Validation error reporting is insufficient

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#339]
We need to improve our diagnostics on validation errors. Referencing a method to obtain this information in an exception is not enough. We need to...
 
- [x] List the validation errors in the exception message.
 
See the TODO on this in `InvalidCommandException.onConstraintViolations()`.

When resolving this issue, we have a chance to fix the placement of `ValidationError` proto type, which is currently in `spine/base/error.proto`. The problem is that `error.proto` now depends on `spine/validate/constraint_violation.proto` which contains the type `ValidationError` encloses.

- [ ] The definition of `ValidationError` should be made in a separate file called `validation_error.proto`. 
- [ ] The file should be under `spine/validate` package.  
- [ ] All the Java types related to validation should be under `org.spine3.validate` package.

**Comment by alexander-yevsyukov** [comment]
@armiol, please see if it's still relevant. If yes, update the description as needed.

**Comment by armiol** [comment]
Resolved in #415.
