### ISSUE TITLE
Provide event idempotency for `ProjectionRepository` instances

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/core-java#356]
In case the Spine-based application is deployed in the Cloud environment, such as Google AppEngine, — or any other that implies the copies of the app running on different instances, — the event delivery may be asynchronous.

At the same time the events are stored to the `EventStore`, backed by the Cloud database (e.g. Google Cloud Datastore).

Therefore the events may be delivered to the target `ProjectionRepository` instances in two ways: via the distributed `EventBus` or via `EventStore` (in the latter case the `Repository` is fetching the events itself on-demand).

Ultimately the same `Event` instance can be delivered to the same `Repository` instance twice.

We need to prevent the data inconsistency in this case.

The idea is to have something like `IdempotencyGuard`, responsible for filtering out the duplicate `Event`s, preventing the repeated delivery of the event, that has already been processed by a certain repository instance. To do that, the `Guard` is caching the delivered `Event` IDs  for a certain timeframe. It acts like a filter for all incoming `Event` instances, ignoring those that has already been taken into account for the target `Projection`.

**Comment by armiol** [comment]
See #733 on this matter.

**Comment by dmdashenkov** [comment]
This is now implemented in the `EntityHistory` system aggregate. This mechanism will, however, be changed once `Inbox` comes out. In any case, such feature is already available.
