### ISSUE TITLE
Entity Columns for Aggregates

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#400]
Currently, [`Entity Columns feature`](https://github.com/SpineEventEngine/core-java/pull/398) is available only for `Projection`s. It's required to add support for `Aggregate`s (in `StandStorage`).

For more info, see `Stand.update()`.

**Comment by dmdashenkov** [comment]
This should be implemented at least partially for `archived` and `deleted` columns, which are present effectively at any entity type.

This change should eliminate double-faced nature of the `RecordStorage` API: currently, it has two ways of writing a record, with and without entity columns.

**Comment by armiol** [comment]
Addressed in `2.0` snapshots.
