### ISSUE TITLE
Generation of `ValidatingBuilder`s

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#408]
The Model Compiler should generate classes derived from `ValidatingBuilder`. Such a builder would generate a message accepting field values as strings. Each such string would pass validation according to constrains defined in proto message definition. Also it would require having a stringifier.

**Comment by IlliaShepilov** [comment]
[PR related to that issue](https://github.com/SpineEventEngine/tools/pull/63)
