### ISSUE TITLE
`RecordStorage` crashes upon `loadAll()` for multiple `Kind`s stored.

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#410]
As long as the current Google Datastore implementation uses the same `RecordStorage` kind to store all the records, the users of `RecordStorage` (such as `ProjectionRepository`) are not able to call `loadAll()`, as it leads to the exception. 

We need to create a separate Datastore kind for each of the routines which rely on `RecordStorage`  for persistence.

**Comment by dmdashenkov** [comment]
For the work related to this issue see [this PR into `gae-java`](https://github.com/SpineEventEngine/gae-java/pull/26).
