### ISSUE TITLE
Allow filters on the `Bus` level

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#413]
- [x] Have `FilterChain` at the level of `Bus`.
- [x] Implement filters for `EventBus`.
- [x] Implement filters for `FailureBus` (if applicable).
- [x] Polis `@SPI` API by removing redundant methods.

**Comment by armiol** [comment]
@dmdashenkov please review. Not sure about the last point. Others look implemented.

**Comment by dmdashenkov** [comment]
Seems done for now.
