### ISSUE TITLE
Spine Time as a core library

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#434]
Create a separate module for values and operations on time - __`spine-time`__:
- [ ] Create GitHub repo
- [ ] Extract all the time-related classes there
- [ ] Leave time-related Stringifiers in `spine-client` code
- [ ] Cover the time-related operations with tests
- [ ] Write the documentation on the library

**Comment by alexander-yevsyukov** [comment]
No longer relevant. Date/time types moved into the `base` project.
