### ISSUE TITLE
Generate repository classes and automatically register them with `BoundedContext`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#486]
So far we do not observe a need to add custom logic to repository classes. Now the repository classes merely define type parameters. 

In order to reduce the number of steps required in supporting a new entity type, let's generate the repository classes by corresponding entity class (which is in turn scaffolded from a properly annotated entity state message).

All the repositories belonging to a `BoundedContext` should be registered via a generated class, which is invoked by the application code after an instance of the `BoundedContext` is built.

If a repository needs a custom storage, it should be constructed manually, passing custom `StorageFactory, and registered with the `BoundedContext` before the call to automatic repository registration. In that case, the automatic registration would bypass creation of the duplicating repository instance.

**Comment by alexander-yevsyukov** [comment]
@armiol, FYI.

**Comment by armiol** [comment]
@alexander-yevsyukov To me. `DefaultRepository.of(RoverBot.class)` qualifies as the desired shortcut. Should we close the issue?

**Comment by alexander-yevsyukov** [comment]
Closing this issue, since `DefaultRepository.of()` addresses the need.
