### ISSUE TITLE
Allow usage of abstract projections

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/core-java#487]
Right now it's not possible to use abstract projections in Spine.

E.g., following code will throw `java.lang.IllegalArgumentException: org.spine3.server.event.EventDispatcherRegistry: No message types are forwarded by this dispatcher` during setup of BoundedContext:
```java
public abstract class AbstractProjection<I, M extends Message> extends Projection<I, M> {
    protected AbstractImagesStatisticsProjection(I id) {
        super(id);
    }

    @Subscribe
    public void on(Event e, EventContext context) {
        doSmth(e, context);
    }
    protected abstract void doSmth(Event e, EventContext context);
}
```
```java
public class Projection extend AbstractProjection<ProjectionId, ProjectionMessage>{
  protected Projection(ProjectionId id) {
        super(id);
    }
  
  @Override
  protected void doSmth(Event e, EventContext context){
    //do smth
  }
}
```

#### Why do we need such feature?

E.g. we have 2 projections with time IDs - one is for Daily statistics and other for Hourly statistics. They, probably will subscribe for the same events and have almost the same logic.
In order to reduce code duplication it would be great, if we could subscribe to events in abstract classes.

#### Current situation

The only possible way to reduce code duplication right now is to override `on` methods and call `super` inside:
```java
public class Projection extend AbstractProjection<ProjectionId, ProjectionMessage>{
  protected Projection(ProjectionId id) {
        super(id);
  }
  
  @Subscribe
  @Override
   public void on(Event e, EventContext context) {
        super(e, context);
   }

  @Override
  protected void doSmth(Event e, EventContext context){
    //do smth
  }
}
```

**Comment by alexander-yevsyukov** [comment]
@dmdashenkov, I think it's possible already. It's how `Policy` was implemented. 

Please have a look into the details of Yuri's request, and see if we can close it.

**Comment by armiol** [comment]
@alexander-yevsyukov @dmdashenkov 

Let's discuss this vocally. 

I don't think it works for Projections in a way Yuri asked for. Also, it is very easy to implement in scope of the Spine core routines. All we need to do is to look up for the annotated methods all the way up the hierarchy. 

But I'd like to also remind everyone we have discussed this feature in terms of meaning and good-bad practices, and definitely decided not to encourage such a behavior.

**Comment by armiol** [comment]
As discussed for several times, we are not going to implement such a feature in the foreseeable future.

We have also agreed to observe more similar use-cases, so that any proposed solution would cover both the described scenario, and other reported scenarios as well.
