### ISSUE TITLE
Enum Entity Columns

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#491]
For now, Entity Columns that end up to be of `enum` type are not supported for the `Any` packing reasons.
It's worth notifying the user about this.
Also, we should come up with the policy of handling the `enum` types. The options are:
 - making them invalid and throwing an exception;
 - making them work through the `int ordinal` or `String name` representation (the way it's done in Hibernate etc.);
 - handling them invisibly from the user using the strategy defined above.

**Comment by armiol** [comment]
Let's mimic [`@Enumerated`](http://docs.oracle.com/javaee/6/api/javax/persistence/Enumerated.html) behavior.

**Comment by dmitrykuzmin** [comment]
Currently, the [Java Enum](https://docs.oracle.com/javase/7/docs/api/java/lang/Enum.html) type of Entity Columns will be supported. The [Protobuf Enum](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Enum) type support can be added later after the functionality supporting Java enums is ready.

**Comment by dmitrykuzmin** [comment]
Done.
