### ISSUE TITLE
Move `UserId` and `TenantId` into the `base` package

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#511]
Now they are in `io.spine.users`. These classes are used by the `io.spine.base` package. Having `UserId` and `TenantId` in the `base` package would minimize inter-package dependency and would free the `users` package for the Users library.

**Comment by alexander-aleksandrov** [comment]
This issue is not relevant anymore. Now both of this files are in 'core-java' project 'core' module.
