### ISSUE TITLE
Validate `Collection`-typed fields properly

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/core-java#536]
At the moment we always validate the `Message` instances, which are appended to `repeated` or `map` fields.

However, we only need to do so if such a field is marked `(valid) = true`. E.g.

```
message Project {

    ProjectId id = 1;
    
    // Each of `Task` messages is validated.
    repeated Task tasks = 2 [(valid) = true];

    // Nothing is validated.
    repeated Comment comments = 3;
}
```

Also, we need to allow using the `(required)` option for collections. In case the `repeated` or `map` field is marked `(required) = true`, it must have at least one item (by the time, when the parent message is built). E.g.

```
message Project {

    ProjectId id = 1;
    
    // `Project` message must have at least one owner 
    // by the time when Project.Builder.build() is executed.
    repeated User owners = 2 [(required) = true];

    // There may be no comments.
    repeated Comment comments = 3;
}
```

Also, the combination of `required` and `valid` is possible and makes sense:

```
message Project {

    ProjectId id = 1;
    
    // `Project` message must have at least one owner 
    // by the time when Project.Builder.build() is executed.
    //
    // Each `User` is validated (e.g. ProjectVBuilder would trigger the validation on-the-fly).
    repeated User owners = 2 [(required) = true, (valid) = true];

    // There may be no comments.
    //
    // But in case there are, each `Comment` message must be valid.
    repeated Comment comments = 3 [(valid) = true];
}
```

In scope of this issue the `FieldValidator` implementations (such as `MessageFieldValidator`) should be modified to achieve the goal.

**Comment by dmdashenkov** [comment]
Resolved.
