### ISSUE TITLE
Prohibit checked exceptions in message handling methods

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#548]
Now it is possible to declare a method annotated (e.g. with `@Assign` or `@React`) as one throwing  checked exception (e.g. `IOException`). 
These methods are called by the dispatching mechanism, which uses Reflection, and catches `RuntimeException`s.
If an annotated method declares (and throws) a checked exception, our code won't catch it, which would cause unpredictable results. 

Therefore, we should analyze method signature on run-time and throw `IllegalStateException` with the diagnostics message. In the future, we would be doing that during compile-time model verification.

**Comment by dmitrykuzmin** [comment]
Done.
