### ISSUE TITLE
Use `Executor`s for dispatching multiple messages

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#550]
There are several places where we dispatch messages in cycles. One of such examples is `AggregateMessageEndpoint.dispatchToMany()`. 

We can dispatch in parallel using a pool of executors, but we don't want to create `Thread` instances left and right.

We should probably have an `ExecutorService` for high- and low- priority pools, and use those pools for dispatching.

**Comment by yuri-sergiichuk** [comment]
As discussed with @armiol a couple of times and taking into account #1275 as well as that `AggregateMessageEndpoint` does not exist anymore, I guess we can safely close this one.

We should not tinker with threads as we never know in what environment the server is gonna be running.
