### ISSUE TITLE
Fail the CI build if artifact publishing fails

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/core-java#558]
At the moment the artifact publishing may fail independently of the successful library build. 

It has happened for several times already due to a Javadoc-related error. In all of those cases the artifacts were not published and could not be used by other teams. At the same time the core committers were not notified — as the build was marked as a successful by the CI server.

We need to be informed of the issues as such. The build at CI server should fail if artifacts were not published.

**Comment by dmytro-grankin** [comment]
Resolved in the series of PRs referenced above.
