### ISSUE TITLE
Make `TestCounterEntity` compatible with declaration convention of `Entity`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#567]
The `TestCounterEntity` is declared as a generic class with `<I>` parameter, which is resolved as types of the enclosing JUnit suite are reified. Because of this we cannot get the value of ID class in `AbstractEntity`. See `AbstractEntity.getStateClass()` for details.

These tests should be re-worked and the workaround in `AbstractEntity.getStateClass()` removed.

**Comment by dmdashenkov** [comment]
`TestCounterEntity` is currently declared with no generic parameters.
