### ISSUE TITLE
Improve `ProjectionRepository` tests

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#570]
Try the following test mutation:

Remove the line:
```java
     store(projection);
```
from `ProjectionEndpoint.deliverNowTo()`. Test should pass, and the only side effect would be missing coverage reported by CodeCov for the method `ProjectionRepository.getStand()`. This is true because the method is not called by `ProjectionEndpoint` because of the removal of the line. We should have at least one failing test instead.

**Comment by alexander-yevsyukov** [comment]
@armiol, FYI.

**Comment by armiol** [comment]
@alexander-yevsyukov addressed in #571.

**Comment by armiol** [comment]
Resolved in #571.
