### ISSUE TITLE
Fix `ProcessManager` versioning

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#589]
Currently, `ProcessManager`s never update their versions as both events and commands are dispatched bypassing the `Transaction`.

**Comment by armiol** [comment]
@illia-shepilov Seems that event reaction now updates the version. We need to ensure that command handling also leads to a version increment. And have tests for both of these cases. 

In tests please make use of `testutil-...` modules. There are some helpers that test entities against commands (passed to `@Assign` method) and events (fed to `@React` method). Maybe you'll find it helpful to append the test utilities with some API to check (or "expect") a particular version.

**Comment by armiol** [comment]
@dmitrykuzmin please feel free to close this one once #893 is merged.

**Comment by dmitrykuzmin** [comment]
Resolved via #893.
