### ISSUE TITLE
Review the default values in Spine enums for neccessity

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/core-java#599]
Since Protobuf 3 the default value for an enumeration seems to be `UNRECOGNIZED` with `-1` field index.

We need to review our enumerations and the code which utilizes them — see if we can get rid of default values, that we manually declare for each of enumerations.

**Comment by vlad-lubenskyi** [comment]
According to documentation: "For enums, the default value is the first defined enum value, which must be 0."

In Java, UNRECOGNIZED value for unrecognized enum values during deserialization. 

So we need to keep explicit default values with index 0.

**Comment by armiol** [comment]
Closing as resolved.
