### ISSUE TITLE
Record origin ID in the `EventContext`

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/core-java#607]
In scope of this issue a traceability of actions needs to be improved.

Currently the chain of `Command` propagation (e.g. `Command` --> `@Assign` handler --> events --> `@React` handler --> events --> ...) is nearly impossible to trace back to the original command instance. Especially it is impossible, being deep down the execution path. 

However, such an opportunity is sometimes a crucial thing. In particular, this is a way to provide idempotence for command-handing entities in relation to commands they handle.

To address that we need to store the origin ID in the `EventContext` for each `Event`. E.g. 

`EventContext.getOriginId() : Any`

In this way the origin ID  will automatically get stored to `EventStore` and will always be available for back-traces.

**Comment by mdrachuk** [comment]
This was implemented in https://github.com/SpineEventEngine/core-java/pull/660.
