### ISSUE TITLE
Eliminate `TypeName`?

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#624]
While fixing #622 it turned out that there are several cases where the `TypeName` type is only used  to retrieve `TypeUrl` instances (via `TypeName.toUrl()`).

Maybe, we should eliminate `TypeName` type and leave `TypeUrl` to act instead of it.

**Comment by alexander-yevsyukov** [comment]
Types have names. That's why we have the thing in the code.
