### ISSUE TITLE
Transform `KnownTypes` into a singleton

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#625]
Currently the `KnownTypes` class is a family of static methods that operate with `static` fields of the class. Even though this class is internal, it would be better to transform it into a singleton with proper encapsulation of properties.

So, instead of:

```java
     if (KnownTypes.getAllUrls().contains(typeUrl)) { ... }
```

we have 

```java
     if (KnownTypes.getInstance().contains(typeUrl)) { ... }
```

De-static-isation of `KnownTypes` would improve its testability and ease integration with CLI and future IDE plug-ins.

**Comment by alexander-yevsyukov** [comment]
@dmdashenkov, FYI, following the question on `TypeName`.

**Comment by armiol** [comment]
Already implemented in `base`. See [base/125](https://github.com/SpineEventEngine/base/pull/125).
