### ISSUE TITLE
Simplify the command router construction for `ProcessManager`s

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#632]
Currently, to create a `CommandRouter` in a `ProcessManger` the user has to do following:
```java
@Assign
CommandRouted on(MyCommand message, CommandContext context) {
    // Create new command messages here.
    return newRouterFor(message, context)
            .add(messageOne)
            .add(messageTwo)
            .routeAll();
}
```
The issue here is that we know both the `message` and `context` when calling this command handler and there is no reason to make the user specify them explicitly.

Moreover, sometimes, the `CommandContext` argument would be redundant if it's not for the `newRouterFor(Message, CommandCotext)` method.

It might be better to hide these arguments from the users and allow them to create instances of `CommandRouter` as `newRouter()`.
Same applies to the `newIteratingRouterFor(Message, CommandCotext)` method.

**Comment by armiol** [comment]
@alexander-yevsyukov this issue may also be affected by your planned changes to command routing from a `ProcessManager`.

**Comment by dmdashenkov** [comment]
This is now obsolete.
