### ISSUE TITLE
Test inner delegate of `DelegatingEventDispatcher`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#639]
See [this coverage report](https://codecov.io/gh/SpineEventEngine/core-java/compare/db0334169b898a904615e3fd29e124883692c2af...654b01efef1bdff6e7261db053bd5bd852dc0c0b/src/server/src/main/java/io/spine/server/event/DelegatingEventDispatcher.java) for details.

**Comment by armiol** [comment]
Resolved in #641.
