### ISSUE TITLE
The `Entity.getState()` behavior does not correspond to the contract

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#647]
According to `io.spine.server.entity.Entity`:
```java
/**
 * Obtains the entity state.
 *
 * <p>This method returns the current state of the entity or,
 * if the entity does not have state yet, the value produced by {@link #getDefaultState()}.
 *
 * @return the current state of default state value
 */
S getState();
```

However, when applying events to an Entity, the `getState()` returns the last "committed" state (i.e. the state before the first applied event).

As a resolution, we may consider splitting `getState()` method into 2:
 - one **always** obtains the latest state;
 - other obtains the "commited" state.

**Comment by armiol** [comment]
Fixed in #1097.
