### ISSUE TITLE
Add tests for PM @React with CommandRouted returned

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/core-java#654]
It seems that there are no unit tests for `@React` handlers that return `CommandRouted` from the Process Managers, while it is the desired way to produce additional commands using `newRouterFor` method.
Something like:
```java
@React
CommandRouted on(OrderConfirmed event, EventContext context) {
final SplitOrder splitOrder = SplitOrderVBuilder.newBuilder()
                                                .setOrderId(event.getOrderId)
                                                .build();
final CommandRouted result = newRouterFor(event, context.getCommandContext())
        .add(splitOrder)
        .routeAll();
return result;
}
```

Plus, it may be useful to add overloaded `newRouterFor` and `newIteratingRouterFor` with `EventContext` as a second parameter.

Also, I'd like to mention that javadocs for `ProcessManager.newRouterFor()` and method parameters should be probably reworded as the accepted `Message` parameter could now be not only `commandMessage`.

**Comment by armiol** [comment]
@alexander-yevsyukov FYI. I think that your current idea will eventually affect this issue.

**Comment by armiol** [comment]
Closing as now it's possible via `@Command`er methods.
