### ISSUE TITLE
License file should not contain brackets

### ISSUE THREAD

**Issue by yuri-sergiichuk** [SpineEventEngine/core-java#655]
Regarding to Apache License appendix `How to apply the Apache License to your work` the license file should not contain placeholders and brackets should be replaced with the real copyright owner and year:

>  To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "{}"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

The following line should be changed:
> Copyright {yyyy} {name of copyright owner}

To smth like:
> Copyright 2018, TeamDev Ltd.

**Comment by alexander-yevsyukov** [comment]
The instruction at the footer says what to do when apply contributor's copyright to a derived work.

See, for example how Guava has a similar instruction in their [COPYING file](https://github.com/google/guava/blob/master/COPYING).
