### ISSUE TITLE
VBuilder is not generated for messages with the same name

### ISSUE THREAD

**Issue by vlad-lubenskyi** [SpineEventEngine/core-java#669]
If you define two messages with the same name in two different packages Spine will generate `VBuilder` only for one of them.

```protobuf
package com.teamdev.bar;

// I will not have a VBuilder.
message VerificationFailureReason {
    ...
}

```

```protobuf
package com.teamdev.foo;

// But I will.
message VerificationFailureReason {
    ...
}

```

**Comment by armiol** [comment]
@yuri-sergiichuk we are no longer using Spine-generated validating builders. But we need to check if our code generation modifies the Protobuf-generated sources properly in this case.
