### ISSUE TITLE
Printing utilities for event history

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#679]
In some cases it is needed to print certain information for a series of events, which may include:
 * full or short type name of an event,
 * its ID,
 * origin command ID,
 * what caused the event,
 * Timestamp of the event,
 * ID of the entity produced the event,
 * etc.

One of the usages, that we already need is printing `RecentHistory`. See PR #666 in which this class was introduced. At the time of writing `RecentHistory` just prints its size because putting all the information about the events would hardly usable in the scope of this class.

As samples for the printing API please consider:
  * `MoreObjects.ToStringHelper` from Guava.
  * `JsonFormat.Printer` from Protobuf.

**Comment by serhii-lekariev** [comment]
Reassigned to @armiol.

**Comment by alexander-yevsyukov** [comment]
Closing as not detailed enough. The projects using Spine address the need somehow. Should we have more detailed needs, we'd revisit the issue.
