### ISSUE TITLE
Include entity version data to the `QueryResponse`

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/core-java#683]
**Preface**

`Aggregate`s and `ProcessManager`s are the versioned entities, which can handle commands. Each modification of their state leads to the version increment. 

At the same time the target version number can be used as a parameter for the `Command`, being a way to escape from updating the stale entities (see `CommandContext.target_version` attribute). I.e. the client may specify the expected version of the target entity, in which as he believes this entity resides. In case the actual entity version differs from the expected version set for the command, the command is rejected — as it clearly has been created with the stale entity state in mind.

**Problem**

Right now it is possible to specify the target version for the command via `CommandFactory.create(Message message, int targetVersion) : Command` API call.

However, at the moment it's not possible to tell the version of entities, which states are returned as a result of `Query` execution. So effectively client-side users aren't able to use the version targeting at all.

**Comment by dmitrykuzmin** [comment]
Resolved via #758.
