### ISSUE TITLE
Code Style Checkers Complain on the "Unused" Private Applier Methods

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#695]
Since recent times, we [agreed](https://github.com/SpineEventEngine/core-java/pull/668) to use package-private (a.k.a. default) access level for event applier methods.

Though, currently, when launching a Spine-based project, the Spine Grade plugin logs following:
```
io.spine.server.model.MethodAccessChecker warnOnWrongModifier
WARNING: Event applier method my.aggregate.Fqn.on() must be declared 'private'.
```

UPD.
It is decided to:
 - use `private` access level for applier methods;
 - use `info` logging level to report the wrong access level;
 - develop custom validation rules for PMD and CheckStyle, which would describe the access level practices.

Also, it is required to change the doc of `@Apply` according to this resolution.

**Comment by alexander-yevsyukov** [comment]
Which static analyzer did cause the unused problem?

Can we tune the analyzers and make the API of aggregates safer instead?

**Comment by alexander-yevsyukov** [comment]
@armiol, the idea to have private appliers is to ensure that nobody can touch an aggregate from outside.  Why did we surrender that easy?

**Comment by dmdashenkov** [comment]
The problem is not on our side. We cannot tune the static code analisers for all our clients.

**Comment by alexander-yevsyukov** [comment]
@dmdashenkov, is it solved (or at least eased) by your recent efforts related to PMD?

**Comment by dmdashenkov** [comment]
It is resolved now. With a bit of configuration of PMD and fix in the Spine own access level check, this is not an issue anymore.
