### ISSUE TITLE
Migrate the framework to JDK 8

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/core-java#700]
As long as Google AppEngine has deprecated JDK 7, it's time for us to do the migration to JDK 8 as well.

Projects to migrate:
* `core-java`;
* `base`;
* `tools`;
* `time`;
* `jdbc-storage`;
* `users`;
* `examples-java`;
* `server-quickstart`;
* `firebase-storage`.

To address:

* Build scripts should have source and targets as `1.8`.
* Migrate Guava's JDK replacements (e.g. `Optional`) to their JDK 8 alternatives.
* Use the latest Guava release (`25` at the moment of issue creation).

To make the changeset smaller, we need to leave all anonymous classes non-converted to lambdas. In future we'll have another round of API review, covering lambdas, `default` implementations in interfaces etc. It's just too big to address right away.

**Versioning**

The version(s) after the migration should become `0.11.0`.

**Comment by dmitrykuzmin** [comment]
By now, all stated repositories are migrated to JDK 8.
