### ISSUE TITLE
Migrate the framework to JUnit 5

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/core-java#701]
After the migration to JDK 8 is done (see #700), we need to migrate to JUnit 5 as well.

The details are to be discussed.

**Comment by dmitrykuzmin** [comment]
The issue was closed automatically via keywords mechanism, as described in https://help.github.com/articles/closing-issues-using-keywords/. It will be really resolved only after all `core-java` modules are migrated to JUnit 5 structure.

**Comment by dmitrykuzmin** [comment]
By now, all stated repositories are migrated to JUnit 5.
