### ISSUE TITLE
Move tests of `EntityBuilder` to proper test suite(s)

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#711]
There are methods of `AggregateShould`  like: 
 * `throw_InvalidEntityStateException_if_state_is_invalid()`
 * `update_valid_entity_state()`

They test the `EntityBuilder`, and not the `Aggregate`. 
Similar methods are in the `AggregatePartShould` test suite.

Because of this they need to be moved into corresponding test suite.

**Comment by dmitrykuzmin** [comment]
Resolved via https://github.com/SpineEventEngine/core-java/pull/767.
