### ISSUE TITLE
`System` Bounded Context Implementation (and the consequences)

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/core-java#733]
**Preface**

At the moment a Spine-based application lacks the information on what's happening under the hood. We have several concepts that require changes to make them usable for the framework end-users — in terms of both coding user experience and ability to operate in a distributed environment:

* `CommandStore`, that is responsible for storing the incoming Commands and their output (Rejections and Errors), but at the same time is not well-suited for reading from the outside.
* `Ack`, being a response to a fired Command and bringing back the acknowledgment (validation errors, rejections, technical failures etc). This concept doesn't stand in the distributed environment, because the validation (`CommandBus` filters) and command rejecting (`@Assign` handlers) very likely take place on different application nodes.
* `Rejection`s, which are stored in `CommandStore` outside the event stream, and therefore can hardly be used by Projections, since the event-rejection-event ordering is lost.
* System-internal rejections `CannotModifyArchivedEntity`, `CannotModifyDeletedEntity`, `EntityAlreadyArchived`, `EntityAlreadyDeleted`, that are too broad to be used outside of the framework code.

Also, we don't store the history of non-event-sourced entities (Projections and Process Managers) and therefore it's virtually impossible to make them idempotent to events and commands they consume via `@React`/`@Subscribe`/`@Assign` methods.

Finally, as `CommandStore` is hardly accessible by the read-side without a lot of additional code —  it's pretty difficult to build something like `Dashboard` Projection on top of this store to understand the state of a Command propagation.

**Idea**

To describe the life of system objects each `BoundedContext` has a "System" `BoundedContext`. The language and events of the system bounded context describe the command propagation, entity lifecycle and entity history (for Projections and ProcessManagers at least).

The events include:

**`CommandLifecycle` (Aggregate per Command instance)**

* `CommandReceived`;
* `CommandAcknowledged`;
* `CommandDispatched`;
* `CommandHandled` / `CommandRejected` / `CommandErrored`.

**`EntityHistory` (Aggregate per Projection / ProcessManager instance)**

* `EntityCreated`;
* `EventDispatchedToSubscriber` (for `Projection`s);
* `EventDispatchedToReactor` (for `ProcessManager`s);
* `CommandDispatchedToHandler` (for `ProcessManager`s);
* `EntityStateUpdated`;
* `EntityDeleted`;
* `EntityArchived`.

These events will make `CommandStore` obsolete, as the information on acknowledgment and rejections/errors resides in the event stream of "System" bounded context.

Also, the history of what's dispatched to `Projection`s and `ProcessManager`s, stored in the respective system aggregate, makes it much easier to provide idempotence for those.

(NOTE: there should be NO "System" bounded context for "System" bounded context :) )

**`Rejection` to Become a Special Kind of `Event`**

The problem of using rejections in a business logic of an end-user application is that they are dispatched to Projections out of sync with events — they use a special `RejectionBus` and they are stored separately (in a `CommandStore`). Due to the same reasons, a catch-up of a newly introduced Projection with millions of events in the stream and thousands of rejections in another stream is nearly impossible.

Therefore `Rejection` should become a special kind of `Event`; in particular:

* Rejection messages are declared in `rejections.proto` as before;
* `EventMessage` marker interface becomes a parent of `RejectionMessage` marker interface.
* Generated Java classes are still descendants of `ThrowableMessage`.
* `Rejection` events are stored in the event stream along with other events.
* As with old-fashion events, it becomes possible to `@React` and `@Subscribe` to rejection events — and they will arrive in order with the old-fashion events, both during runtime dispatching and catch-up.

`RejectionBus` and `RejectionSubscriber` become obsolete. 

**Entity Updates in `@Subscribe`**

At the moment there is a `Stand`, storing the latest states of the entities and serving as a subscription hub for those who wish to access the read-side through `SubscriptionService`.

With the proposed `EntityStateUpdated` event (see above) it should become possible to `@Subscribe` to the entity state updates as follows:

```java
@Subscribe
on(ProjectDetails projection[, EventContext context]) { ... }
```
where the `context` is a context of a system event.

To store the latest states of `Aggregate`s it is proposed to create `Projection`s in the "System" bounded context — for those aggregates with proper `Visibility` level. Thus `Stand` will no longer store anything, but serve as front-facing API for `SubscriptionService` and `QueryService`.

Also, as emitting the entity state updates results into an event, the event stream may get polluted with those very quickly. So by default no entities emit their state update events. To enable such a feature a framework user should define a predicate function in the repository of the respective entity. 

The function makes a decision basing on

* the previous entity state (before transaction) + version, 
* new entity state (after transaction) + version, 
* the message (handled command or reacted-on event) that triggered the change + its context (assuming `oneof` command message + `CommandContext` OR event message + `EventContext`),
* (TBD) recent history of events?

By default such a function predicate returns `false` which means "do not post the update". Once overridden by a user, it may return `true`, which means "post this particular entity state update as an event".

Also, as long as the `EntityStateUpdate` events may be routed to Projections, they have to reside in the domain event stream as well — to keep those in order with the rest of domain events that are read during replay or catch-up.

**Client Subscriptions Through `Stand`**

After losing its storage functionality (see above), it would be nice to allow clients to subscribe to everything available on the server-side via `@Subscribe` annotation. The following code snippet illustrates the idea:

```java
// client-side code:

public final class ProjectSubscriber extends EventSubscriber {

        @Subscribe
        public void on(ProjectCreated eventMsg) {}

        @Subscribe
        public void on(ProjectDetails stateUpdateMsg) {}

        @Subscribe
        public void on(CannotCreateProject rejectionEventMsg) {}
}

// ...
ActorContext actorContext = ...

StandClient standClient = StandClient.of(channel); // wrap around `SubscriptionServiceStub`
EventSubscriber subscriber = new ProjectSubscriber();
standClient.register(subscriber, actorContext);
```

Such an opportunity will significantly widen the number of options for building rich clients for Spine server applications.

**Comment by armiol** [comment]
@alexander-yevsyukov @dmdashenkov FYI.

**Comment by dmdashenkov** [comment]
After a discussion, it was decided that `Aggregate`s have corresponding `EntityHistory` instances as well as `Projections`/`ProcessManagers`.

As the consequence, the `EntityHistory` has another event `EventPassedToApplier`.

Also, the aggregate has events reverting `EntityArchived` and `EntityDeleted`, so that any lifecycle flags changes are covered.

**Comment by armiol** [comment]
@dmdashenkov please see my edits in `Entity Updates in @Subscribe` section. I have appended it with some details on posting the `EntityStateUpdated` event.

**Comment by armiol** [comment]
Closing as most of the parts is implemented. The rest became obsolete.
