### ISSUE TITLE
Synchronization In `DispatchQueue`

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#746]
Currently, the `DispatchQueue.add(...)` is a `synchronized` method. This was required in order to fix multithreading bugs, revealed in the tests.

Now, it is required to:
 - revisit the approach and try to avoid synchronization;
 - if the previous step is failed, rewrite the synchronization using `java.util.concurrent` instead of native mutexes.

**Comment by dmdashenkov** [comment]
It is now known that the synchronization results in a deadlock.

It is expected that the deadlock will be eliminated by the `Inbox`.

**Comment by armiol** [comment]
The `DispatchQueue` has been removed a while ago.
