### ISSUE TITLE
Rename Test Suite from `ProjectionEventTest` to `ProjectionTest`

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#753]
The test suite conflicted with the class with the same name and package in another module, thus was renamed.

The original name (`ProjectionTest`) should be restored as soon as we get rid of split-packaging in the whole framework or, at least, the `core-java` repository.

**Comment by dmdashenkov** [comment]
@vlad-lubenskyi, FYI.

**Comment by alexander-yevsyukov** [comment]
The test suite is now named `ProjectionShould` with appropriate `@apiNote` on the name. This is enough to make it clear, and is better than have two classes of the same name.
