### ISSUE TITLE
Detect the usage of `Message.Builder` and advice using `...VBuilder` in the codebase

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/core-java#769]
The validating builders are created to eliminate potential programming mistakes on building the `Message` violating the validation rules. Therefore we need to provide a way to track the cases where a regular `Builder` is used and warn the end-user on that.

It seems that creating a [custom Error Prone check](https://errorprone.info/docs/plugins) is the way to do it. 

Ideally we should be able to configure a severity of the bug (warning, error etc) per Gradle module or even per package, if possible. 

Also a way to suppress this check per-expression/per-class is needed — in case we really need to use a Protobuf-generated builder of `Message`. For instance the test code of our validation framework has some invalid `Message` instances created on purpose using the `Message.Builder` mechanism.

**Comment by dmitrykuzmin** [comment]
Closed via https://github.com/SpineEventEngine/base/pull/180.
