### ISSUE TITLE
A `ProcessManager` can ignore a command

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#773]
The body of `CommandHandlerMethod.invoke()` currently can accept an empty list of event messages generated as the result of the method execution.

Attempt to prevent this via
```java
checkState(!events.isEmpty();
```
Results in several broken tests in `ProcessManagerRepositoryTest`. It turns out that test environment classes if this test suite do violate the contract of command handling methods. See `ProcessManagerRepositoryTestEnv.TestProcessManager`.

The problem is that even if handling method of a `ProcessManager` returns `Empty`, it would result in no events generated. Chances are that the same would be possible for `Aggregate`s.

The following needs to be done:
  1. Test environment classes for `ProcessManagerRepositoryTest` need to be adjusted to stop violating the contract of command handling methods.
  2. The `CommandHandlerMethod.invoke()` should have the check for non-empty list of events. 
      (I'm adding TODO with the reference to this issue in this method.)
  3. Inform current users of the framework on the change of the behaviour of `ProcessManager`s.

**Comment by dmitrykuzmin** [comment]
Resolved via https://github.com/SpineEventEngine/core-java/pull/785.
