### ISSUE TITLE
Disallow a command handler method declare a `RuntimeException` thrown

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#774]
Now `CommandHandlerMethod.checkThrownExceptions()` check for both `ThrowableMessage` _and_ `RuntimeException`.

Although, such a method can throw a rejection, throwing a `RuntimeException` can be confusing.
Exceptions may occur, and we'd generate an `Error` in response to them, but why encourage it?

The problem is that `ThrowableMessage`s have corresponding proto messages, and as such are platform neutral. This is not the case for `RuntimeExceptions`. What if part of the business logic that handles such a command would need to be ported to another language?

Therefore `CommandHandlerMethod.checkThrownExceptions()` should be modified to disallow `RuntimeException`s. And the corresponding tests should be added.

**Comment by dmitrykuzmin** [comment]
Resolved via https://github.com/SpineEventEngine/core-java/pull/786.
