### ISSUE TITLE
Implement generation of factory methods for UUID-based `Message` identifiers

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/core-java#778]
Let's suppose there is a message
```
message ProjectId {
    // UUID-based generated value.
    string uuid = 1 [(required) = true];
}
```

It is not too convenient to build the messages of this type via 
```java
 ProjectId id = ProjectIdVBuilder
                .newBuilder()
                .setUuid(Identifier.newUuid())
                .build();
```

Instead we can generate an interface (e.g. `UniqueId`) with the `default` methods:
* `generate(): <I>` — creating an instance of the target type filling its only field with the freshly generated UUID value;
* `of(String): <I>` — creating an instance of target type with the given value, validating it beforehand.

This interface should become a parent for the Java-generated code for the messages like this. Such an extension is allowed by the Protobuf compiler.

We should do it automatically for the messages that have exactly one required field named `uuid`.

In future we may introduce an option to allow similar factory method generation for other common cases. But let's start with this one.

**Comment by dmitrykuzmin** [comment]
Closed via https://github.com/SpineEventEngine/base/pull/267.
