### ISSUE TITLE
Move Command Scheduling to System Bounded Context

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#799]
Currently, `CommandScheduler` is a `CommandBus` filter. 
We should move command scheduling to the System BC so that it is not dependent on the main application process.

The `CommandBus` filter should turn into a tap, which would send a command to schedule a command handling job to a `ProcessManager` in the System BC.
The `SystemGateway` should start working in both directions - posting commands into system _and_ into domain bounded context.

**Comment by armiol** [comment]
This is going to be implemented via `Inbox`.
