### ISSUE TITLE
Document using `Optional` as the allowed result in reacting methods

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#805]
Can I write something like:

```java
@React(external=true) 
Optional<TaskAssigned> on(UserCreated event) { ... }
```

This would make the optional nature of generated event obvious.

**Comment by armiol** [comment]
Yes, it is possible.

**Comment by alexander-yevsyukov** [comment]
@armiol, we need to update documentation because currently `@React` does enumerate this option.

Because of these Backlog guys write this:
```java
@React(external = true)
    EitherOf2<IssueImported, Nothing> handle(GitHubIssueReceived e) { ... }
```

**Comment by armiol** [comment]
Documented a while ago.
