### ISSUE TITLE
Mark generated messages with corresponding marker interfaces

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#818]
Those from `commands.proto` should be `CommandMessage`, `events.proto` -> `EventMessage`, 
`rejections.proto` -> `RejectionMessage`.

As per #733, `RejectionMessage` should extend `EventMessage`.

`EventContext` and `CommandContext` should implement `MessageContext` marker interface.

**Comment by armiol** [comment]
Related to #911.
