### ISSUE TITLE
Querying entities with non Message IDs 

### ISSUE THREAD

**Issue by dmytro-kashcheiev** [SpineEventEngine/core-java#837]
As far as I know, right now Spine provides the possibility to use: `String`, `int`, `long`, `Message` as Entity ID (Even if it's bad practice to use primitives as ID). 
But on the other hand, right now there is no possibility to query such entities using: `ActorRequestFactory.query().byIds(...)`, as far as `Set<? extends Message> ids` is expected as a parameter.

**Comment by mdrachuk** [comment]
Spine does provide a way to create `Query` instance using primitive ids using `QueryBuilder#byId(...)`.
As for the `QueryFactory`, it will be updated to allow primitive IDs in PR #836.
