### ISSUE TITLE
Model verification cannot access known types

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#842]
The model verification mechanism (see `model/model-assembler` and `model/model-verifier`) is currently broken.

The mechanism uses the handler method signatures API, which, in turn, uses `KnownTypes`. Compile-time `KnownTypes` are not the same as the runtime ones.

To fix this, it's proposed to make `KnownTypes` mutable (appendable). This way, we'll be able to make all the user-defined types known at compile-type.

**Comment by alexander-yevsyukov** [comment]
Some things depend on immutability of `KnownTypes`. For example, `io.spine.json.Json`, which takes type registry. Changing it would probably require forcing users to create all the Json- and stringification machinery in their code.

**Comment by alexander-yevsyukov** [comment]
> Compile-time KnownTypes are not the same as the runtime ones.

How does that happen? It doesn't sound right.

**Comment by alexander-yevsyukov** [comment]
> Model Verification Is Broken

This title is too generic. Please change it to describe the problem in a specific way.
