### ISSUE TITLE
Improve JavaScript usability of spine.net.Url with Record value

### ISSUE THREAD

**Issue by dmytro-kashcheiev** [SpineEventEngine/core-java#843]
Right now when you are using `spine.net.Url` message on the server(Java) side you have a lot of utilities to work with these urls(`io.spine.net.Urls`). 

When you want to use `spine.net.Url` with the `Record` type of value on the client side (JavaScript) it's rly uncomfortable to work with it as far as you have no stringifier utilities, and there is no simple way to receive `raw` representation of this value. So far it should be great to have something equal to `io.spine.net.Urls` on the JS side or have 'rawUrl'  within `Record` representation of Url value.

**Comment by alexander-yevsyukov** [comment]
The `Record` part of `Url` was removed. So, this issue is no longer applicable.
