### ISSUE TITLE
Improve the API of `AbstractExpected` and its descendants

### ISSUE THREAD

**Issue by dmytro-grankin** [SpineEventEngine/core-java#879]
### Commands and events verification

The API of `MessageProducingExpected` has some flaws:

- `producesCommands(Class<?>... commandClasses)` doesn't verify the order of command classes. The ability to verify the order should be added.
- `producesCommands(Class<?>... commandClasses)` doesn't provide a way to verify the state of commands. The overloaded version — `producesCommands(CommandMessage... commands)` would be handy.

The same is true for the `producesMessages` method.

### Rejections verification

The API for the rejections verification only present in `CommandHandlerExpected`, but it is missing in `CommanderExpected`. It is tricky place and ideally the API should be available only in `PmCommandOnCommandTest` and not available in `PmCommandOnEventTest`.

And again, `CommandHandlerExpected` has only `throwsRejection(Class<? extends Message> rejectionClass)`. The overloaded version, which accepts `ThrowableMessage` would be handy.

### State verification

And the possible impovement for the state verification:

```java
expectThat(entity).hasState(Message)
```

Now, it is not always convenient use `hasState(Consumer validator)`.

**Comment by dmytro-grankin** [comment]
@alexander-yevsyukov here is the inconveniences I have faced with test utils.

**Comment by vlad-lubenskyi** [comment]
@dmytro-grankin you can test rejections using `CommandHandlerExpected`

**Comment by dmytro-grankin** [comment]
@vlad-lubenskyi I updated the issue, `CommanderExpected` misses the feature with rejections.

**Comment by dmdashenkov** [comment]
As this test framework is now deleted, this issue is no longer relevant.
