### ISSUE TITLE
Calculate `zoneOffset` by `zoneId` in `TestActorRequestFactory`

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#885]
Now we pass two parameters: `zoneOffset` and `zoneId`. Before `ZoneId` type was introduced, there used to be only one parameter, `zoneOffset`. It is possible to calculate the current offset by the zone ID. So, there's no sense in passing two parameters.

**Comment by serhii-lekariev** [comment]
https://github.com/SpineEventEngine/core-java/pull/915 has addressed the described issue.
` TestActorRequestFactory`'s ctor now accepts 2 parameters, and the zone offset is calculated based on the specified zone ID.
