### ISSUE TITLE
Unable to use `Pair<A, Optional<B>` as a result of a commander method

### ISSUE THREAD

**Issue by dmytro-grankin** [SpineEventEngine/core-java#894]
For the commander declaration:

```java
@Command
Pair<AssignTask, Optional<StartTask>> handle(CreateTask command)
```

Which returns:

```java
Paith.withNullable(assignTask, null)
```

A `ClassCastException` is thrown with the following message `Empty cannot be cast to CommandMessage`. It happens in `Split.addAll(...)`.

**Comment by dmitrykuzmin** [comment]
Resolved via #895.
