### ISSUE TITLE
Do not allow registering repository with duplicated entity state

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#901]
It should not be possible to register an repository entity of which has a state type, which is already known to `BoundedContext`.

**Comment by dmdashenkov** [comment]
@serhii-lekariev, this seems to be a regression. This check was once implemented. Please investigate.

**Comment by serhii-lekariev** [comment]
https://github.com/SpineEventEngine/core-java/pull/919 has covered the restriction of only having one per state message type with a test.
