### ISSUE TITLE
Remove build hack for `WithLifecycle` after Spine Proto Compiler supports optional generation of interfaces

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#909]
The code of `server/build.gradle` has the task for removing generated `WithLifecycle.java`. The task is needed because there is handcrafted `WithLifecycle` class, which is used in code generation, so that `EntityRecord` implements it.

The hack can be removed after Spine Proto Compiler supports optional generation of interfaces via extended syntax of `is` option. Once it's available the following needs to be done:

- [ ]  New option should be used in `entity.proto`.
   Presumably, it would look like:
  ```proto
  option (is).java_type = "WithLifecycle" ;
  ```
  This syntax assumes that `generate` attribute equals `false`.

- [ ]  The task `deleteGeneratedWithLifecycleJava` and dependence on it is removed from `server/build.gradle`.

**Comment by alexander-yevsyukov** [comment]
@armiol, I could not find an issue for the improvement of new `is` option syntax. I presume it's no in the Spine org. at all. If so, please create and link to this request.

**Comment by armiol** [comment]
See #911.
