### ISSUE TITLE
Unexpected NPE when scanning for entity columns

### ISSUE THREAD

**Issue by dmdashenkov** [SpineEventEngine/core-java#912]
If an entity class declares a `public` setter of getter method, `ColumnReader` assumes the method is a property of a bean, i.e. an entity column. When trying to find an annotated version of the method in the class hierarchy (and failing to do so), `ColumnReader` throws an NPE with no message.

The expected behaviour is either
 - ignoring the method at all, possibly, with a warning log;
 - failing with a more descriptive exception and message.

**Comment by dmdashenkov** [comment]
@armiol, let's discuss this issue, please.

**Comment by armiol** [comment]
@dmdashenkov In case there is a getter with no `@Column` annotation, we just ignore it.

**Comment by serhii-lekariev** [comment]
This issue has been addressed in https://github.com/SpineEventEngine/core-java/pull/917.
