### ISSUE TITLE
Allow deleting/archiving process managers upon a rejection or an event

### ISSUE THREAD

**Issue by mdrachuk** [SpineEventEngine/core-java#920]
This issue opens up a topic of "terminal" events for processes.

The vast majority of the processes have a distinct end-of-life marker. In most cases that's an event (or several events) emitted by the process manager. Typically the framework users would have to write a code to mark the process manager deleted before emitting the terminal events. It is quite possible right now, it just some boilerplate to keep in mind.

However a process may also end emitting a rejection. In this case an engineer is not able to change neither the entity state nor its lifecycle, as they are automatically reverted after an exception — which is a rejection by its nature.

We may automate this.

An event or a rejection declared as terminal signalizes the framework this process manager can be safely deleted or archived. In this case the framework marks the process manager correspondingly in scope of the same transaction. 

I would imagine the process manager declaration as follows.
```
message SignInProcess {
    option (entity).kind = PROCESS_MANAGER;

    // The process is deleted in case `UserSignedIn` is emitted or `CannotAuthenticateUser` is thrown.
    option (lifecycle).delete_upon = "UserSignedIn, CannotAuthenticateUser";

    // Another option is to archive automatically:
    // option (lifecycle).archive_upon = "..."

    // Here goes the process state description.
}
```

**Comment by dmitrykuzmin** [comment]
In the end, we took the other approach and abandoned the idea of having options that describe entity behavior. 

Automatic entity archivation/deletion via repository was implemented in #974.
