### ISSUE TITLE
Avoid code duplication for handling rejections and posting events

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#927]
We have code duplication in `AggregateRepository` and `ProcessManagerRepository`. 

Duplicated code is in:
 * `onError()` methods, which is understood since both repositories dispatch commands and handle rejections similarly.
 * `postEvents()` methods, which does filtering and posting to `EventBus`.

We cannot have a common interface for these repositories because it would publicly expose methods for accessing `EventBus`, which are currently `protected`.

One of the option could be to extend `CommandErrorHandler` with an ability to deal with posting rejections.

**Comment by armiol** [comment]
The code duplication has been removed by introducing `EventProducingRepository` interface with the default implementation of posting the events and `DispatchCommand` method object which handles the rejected commands. As for the `CommandErrorHandler`, it no longer exists.

Closing as obsolete.
