### ISSUE TITLE
Core types are not visible under `model-verifier` module

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#928]
For example, an attempt to use `UserId` in the `test/proto` fails because `extracted-include-protos` contain only protos from `base` and its dependencies like `time`. Core protos are not there.

**Comment by dmdashenkov** [comment]
This is due to the `implementation` config (see [this issue](https://github.com/SpineEventEngine/base/issues/126)). If you want to use core Protobuf types in `model-verifier`, use 
```gradle
compile project(':server')
```
instead of
```gradle
implementation project(':server')
```

By now, there was no reason to do so, hence the configuration.

**Comment by dmdashenkov** [comment]
Closing this issue as a duplicate. See [base/#126](https://github.com/SpineEventEngine/base/issues/126) for the original issue.
