### ISSUE TITLE
Migrate state of test environment entities to using generated classes

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#946]
... not `StringValue` or some other standard Protobuf types.

We do not want to give framework users misleading examples even in the test code.

**Comment by alexander-yevsyukov** [comment]
See `AbstractEntityTest`. The `AnEntity` test environment class uses `StringValue` as the state.

**Comment by armiol** [comment]
As the state of an `Entity` now must extend `EntityState`, the codebase no longer has the described issues.
